/** KARP ギャラリー画像リスト。新規追加分は連番を維持したまま表示順の先頭へ置く。 */
export const KARP_IMAGES = [
  { id: "55", src: "/karp/karp-055.webp", alt: "紫色のセーター姿で眼鏡を直すAlex Karp" },
  { id: "56", src: "/karp/karp-056.webp", alt: "青いジャケットと帽子姿でVサインをするAlex Karp" },
  { id: "57", src: "/karp/karp-057.jpg", alt: "テレビ番組のセットで着席し、横を向くAlex Karp" },
  { id: "58", src: "/karp/karp-058.jpg", alt: "装飾のある壁とテーブルの前に座るAlex Karp" },
  { id: "48", src: "/karp/karp-048.webp", alt: "建物の入口で両腕を広げる、帽子とサングラス姿のAlex Karp" },
  { id: "49", src: "/karp/karp-049.jpg", alt: "建物の入口で片手を上げるAlex Karp" },
  { id: "50", src: "/karp/karp-050.jpg", alt: "帽子とサングラス姿で片手を上げるAlex Karp" },
  { id: "51", src: "/karp/karp-051.jpg", alt: "着席して両手で身振りを交えながら話すAlex Karp" },
  { id: "52", src: "/karp/karp-052.jpg", alt: "室内に立つ、白いTシャツ姿のAlex Karp" },
  { id: "53", src: "/karp/karp-053.jpg", alt: "室内の出入口で両腕を広げるAlex Karp" },
  { id: "54", src: "/karp/karp-054.jpg", alt: "木目の壁を背景にした、眼鏡姿のAlex Karpの肖像" },
  { id: "41", src: "/karp/karp-041.jpg", alt: "Alex Karp photo 041" },
  { id: "42", src: "/karp/karp-042.jpg", alt: "Alex Karp photo 042" },
  { id: "43", src: "/karp/karp-043.jpg", alt: "Alex Karp photo 043" },
  { id: "44", src: "/karp/karp-044.jpg", alt: "Alex Karp photo 044" },
  { id: "1", src: "/karp/karp-001.jpg", alt: "Alex Karp photo 001" },
  { id: "2", src: "/karp/karp-002.jpg", alt: "Alex Karp photo 002" },
  { id: "3", src: "/karp/karp-003.jpg", alt: "Alex Karp photo 003" },
  { id: "4", src: "/karp/karp-004.jpg", alt: "Alex Karp photo 004" },
  { id: "5", src: "/karp/karp-005.jpg", alt: "Alex Karp photo 005" },
  { id: "6", src: "/karp/karp-006.jpg", alt: "Alex Karp photo 006" },
  { id: "7", src: "/karp/karp-007.jpg", alt: "Alex Karp photo 007" },
  { id: "8", src: "/karp/karp-008.jpg", alt: "Alex Karp photo 008" },
  { id: "9", src: "/karp/karp-009.jpg", alt: "Alex Karp photo 009" },
  { id: "10", src: "/karp/karp-010.jpg", alt: "Alex Karp photo 010" },
  { id: "11", src: "/karp/karp-011.jpg", alt: "Alex Karp photo 011" },
  { id: "12", src: "/karp/karp-012.jpg", alt: "Alex Karp photo 012" },
  { id: "13", src: "/karp/karp-013.jpg", alt: "Alex Karp photo 013" },
  { id: "14", src: "/karp/karp-014.jpg", alt: "Alex Karp photo 014" },
  { id: "15", src: "/karp/karp-015.jpg", alt: "Alex Karp photo 015" },
  { id: "16", src: "/karp/karp-016.jpg", alt: "Alex Karp photo 016" },
  { id: "17", src: "/karp/karp-017.jpg", alt: "Alex Karp photo 017" },
  { id: "18", src: "/karp/karp-018.jpg", alt: "Alex Karp photo 018" },
  { id: "19", src: "/karp/karp-019.jpg", alt: "Alex Karp photo 019" },
  { id: "20", src: "/karp/karp-020.jpg", alt: "Alex Karp photo 020" },
  { id: "21", src: "/karp/karp-021.jpg", alt: "Alex Karp photo 021" },
  { id: "22", src: "/karp/karp-022.jpg", alt: "Alex Karp photo 022" },
  { id: "23", src: "/karp/karp-023.jpg", alt: "Alex Karp photo 023" },
  { id: "24", src: "/karp/karp-024.jpg", alt: "Alex Karp photo 024" },
  { id: "25", src: "/karp/karp-025.jpg", alt: "Alex Karp photo 025" },
  { id: "26", src: "/karp/karp-026.jpg", alt: "Alex Karp photo 026" },
  { id: "27", src: "/karp/karp-027.jpg", alt: "Alex Karp photo 027" },
  { id: "28", src: "/karp/karp-028.jpg", alt: "Alex Karp photo 028" },
  { id: "29", src: "/karp/karp-029.jpg", alt: "Alex Karp photo 029" },
  { id: "30", src: "/karp/karp-030.jpg", alt: "Alex Karp photo 030" },
  { id: "31", src: "/karp/karp-031.jpg", alt: "Alex Karp photo 031" },
  { id: "32", src: "/karp/karp-032.jpg", alt: "Alex Karp photo 032" },
  { id: "33", src: "/karp/karp-033.jpg", alt: "Alex Karp photo 033" },
  { id: "34", src: "/karp/karp-034.jpg", alt: "Alex Karp photo 034" },
  { id: "35", src: "/karp/karp-035.jpg", alt: "Alex Karp photo 035" },
  { id: "36", src: "/karp/karp-036.jpg", alt: "Alex Karp photo 036" },
  { id: "37", src: "/karp/karp-037.jpg", alt: "Alex Karp photo 037" },
  { id: "38", src: "/karp/karp-038.jpg", alt: "Alex Karp photo 038" },
  { id: "39", src: "/karp/karp-039.jpg", alt: "Alex Karp photo 039" },
  { id: "40", src: "/karp/karp-040.jpg", alt: "Alex Karp photo 040" },
];
